library(KoNLP)
hotel <- readLines("C:/boxak/Rstudy/hotel.txt")
hotel2<- extractNoun(hotel)
hotelUn <- unlist(hotel2)
hotelUn2<-gsub("[^가-힣]", "",hotelUn)
hotelUn3<-gsub(" ", "",hotelUn2)
hangul<- Filter(function(x) {nchar(x) >= 2}, hotelUn3)
word_table <- table(hangul)
final <- sort(word_table, decreasing = T)
hotelResult<-head(final, 10)
names(hotelResult)
