library(KoNLP)
hotel <- readLines("C:/boxak/Rstudy/hotel.txt")
hotel2<- extractNoun(hotel)
hotelUn <- unlist(hotel2)
hotelUn2<-gsub("[^가-힣]","",hotelUn)
hangul<- Filter(function(x) {nchar(x) >= 2}, hotelUn2)
word_table <- table(hangul)
final <- sort(word_table, decreasing = T)
hotelResult<-head(final, 10)
hotelD<- as.data.frame(hotelResult)